
[core]
	engine = pg
	target = dev


[target "de01"]
	uri = db:pg://developer@pg01.claviron.app/roma

[target "de02"]
	uri = db:pg://developer@pg02.claviron.app/roma

[target "dev"]
	uri = db:pg:roma

